// DO NOT EDIT
// This file is autogenerated by gen_checks.py
use crate::checks::PatchKind::*;
use crate::checks::*;

pub const CHECKS: &[(&'static str, &'static [PatchKind])] = &[
    (
        "Upper Skyloft - Fledge's Gift",
        &[
            FlowById {
                file: "114-Friend",
                index: 16,
            },
            Oarc {
                stage: "F001r",
                layer: 3,
            },
            Oarc {
                stage: "F001r",
                layer: 4,
            },
        ],
    ),
    (
        "Upper Skyloft - Owlan's Gift",
        &[
            FlowById {
                file: "108-ShinkanA",
                index: 169,
            },
            Oarc {
                stage: "F000",
                layer: 4,
            },
            Oarc {
                stage: "F000",
                layer: 6,
            },
        ],
    ),
    (
        "Upper Skyloft - Sparring Hall Chest",
        &[TBox {
            stage: "F009r",
            room: 0,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Central Skyloft - Potion Lady's Gift",
        &[
            FlowById {
                file: "106-DrugStore",
                index: 44,
            },
            Oarc {
                stage: "F004r",
                layer: 0,
            },
        ],
    ),
    (
        "Central Skyloft - Waterfall Cave First Chest",
        &[TBox {
            stage: "D000",
            room: 0,
            layer: 0,
            tbox_id: 67,
        }],
    ),
    (
        "Central Skyloft - Waterfall Cave Second Chest",
        &[TBox {
            stage: "D000",
            room: 0,
            layer: 0,
            tbox_id: 68,
        }],
    ),
    (
        "Central Skyloft - Rupee Waterfall Cave Crawlspace",
        &[Item {
            stage: "D000",
            room: 0,
            layer: 0,
            flag: 88,
        }],
    ),
    (
        "Upper Skyloft - Chest near Goddess Statue",
        &[TBox {
            stage: "F000",
            room: 0,
            layer: 0,
            tbox_id: 71,
        }],
    ),
    (
        "Upper Skyloft - First Goddess Sword Item in Goddess Statue",
        &[
            FlowByName {
                file: "107-Kanban",
                name: "Fi give Goddess Statue item 1",
            },
            Oarc {
                stage: "F008r",
                layer: 1,
            },
        ],
    ),
    (
        "Upper Skyloft - Second Goddess Sword Item in Goddess Statue",
        &[
            FlowByName {
                file: "107-Kanban",
                name: "Fi give Goddess Statue item 2",
            },
            Oarc {
                stage: "F008r",
                layer: 1,
            },
        ],
    ),
    (
        "Central Skyloft - Bazaar Goddess Chest",
        &[TBox {
            stage: "F004r",
            room: 0,
            layer: 0,
            tbox_id: 93,
        }],
    ),
    (
        "Central Skyloft - Shed Chest",
        &[TBox {
            stage: "F000",
            room: 0,
            layer: 0,
            tbox_id: 70,
        }],
    ),
    (
        "Central Skyloft - Shed Goddess Chest",
        &[TBox {
            stage: "F000",
            room: 0,
            layer: 0,
            tbox_id: 79,
        }],
    ),
    (
        "Central Skyloft - West Cliff Goddess Chest",
        &[TBox {
            stage: "F000",
            room: 0,
            layer: 0,
            tbox_id: 78,
        }],
    ),
    (
        "Central Skyloft - Floating Island Goddess Chest",
        &[TBox {
            stage: "F000",
            room: 0,
            layer: 0,
            tbox_id: 91,
        }],
    ),
    (
        "Central Skyloft - Waterfall Goddess Chest",
        &[TBox {
            stage: "F000",
            room: 0,
            layer: 0,
            tbox_id: 80,
        }],
    ),
    (
        "Upper Skyloft - Pumpkin Archery -- 600 Points",
        &[
            FlowById {
                file: "114-Friend",
                index: 99,
            },
            Oarc {
                stage: "F000",
                layer: 4,
            },
            Oarc {
                stage: "F000",
                layer: 6,
            },
        ],
    ),
    (
        "Upper Skyloft - In Zelda's Closet",
        &[chest {
            stage: "F001r",
            room: 6,
            layer: 0,
            flag: 32,
        }],
    ),
    (
        "Central Skyloft - Item in Bird Nest",
        &[Item {
            stage: "F000",
            room: 0,
            layer: 0,
            flag: 13,
        }],
    ),
    (
        "Central Skyloft - Parrow's Gift",
        &[
            FlowById {
                file: "115-Town2",
                index: 230,
            },
            FlowById {
                file: "115-Town2",
                index: 733,
            },
            Oarc {
                stage: "F000",
                layer: 4,
            },
            Oarc {
                stage: "F000",
                layer: 6,
            },
            Oarc {
                stage: "F005r",
                layer: 0,
            },
        ],
    ),
    (
        "Upper Skyloft - Cawlin's Letter",
        &[
            FlowById {
                file: "115-Town2",
                index: 166,
            },
            Oarc {
                stage: "F001r",
                layer: 0,
            },
        ],
    ),
    (
        "Central Skyloft - Wryna's Crystals",
        &[
            FlowById {
                file: "118-Town3",
                index: 144,
            },
            Oarc {
                stage: "F006r",
                layer: 0,
            },
        ],
    ),
    (
        "Central Skyloft - Peater/Peatrice's Crystals",
        &[
            FlowById {
                file: "109-TakeGoron",
                index: 79,
            },
            FlowById {
                file: "123-Town5",
                index: 316,
            },
            Oarc {
                stage: "F018r",
                layer: 0,
            },
            Oarc {
                stage: "F019r",
                layer: 0,
            },
        ],
    ),
    (
        "Central Skyloft - Parrow's Crystals",
        &[
            FlowById {
                file: "115-Town2",
                index: 814,
            },
            Oarc {
                stage: "F000",
                layer: 4,
            },
            Oarc {
                stage: "F000",
                layer: 6,
            },
            Oarc {
                stage: "F005r",
                layer: 0,
            },
        ],
    ),
    (
        "Upper Skyloft - Fledge's Crystals",
        &[
            FlowById {
                file: "115-Town2",
                index: 325,
            },
            Oarc {
                stage: "F001r",
                layer: 0,
            },
        ],
    ),
    (
        "Skyloft Village - Bertie's Crystals",
        &[
            FlowById {
                file: "115-Town2",
                index: 125,
            },
            Oarc {
                stage: "F014r",
                layer: 0,
            },
        ],
    ),
    (
        "Upper Skyloft - Ghost/Pipit's Crystals",
        &[
            FlowById {
                file: "115-Town2",
                index: 522,
            },
            FlowById {
                file: "115-Town2",
                index: 641,
            },
            Oarc {
                stage: "F001r",
                layer: 0,
            },
        ],
    ),
    (
        "Skyloft Village - Sparrot's Crystals",
        &[
            FlowById {
                file: "118-Town3",
                index: 141,
            },
            Oarc {
                stage: "F013r",
                layer: 0,
            },
        ],
    ),
    (
        "Skyloft Village - Mallara's Crystals",
        &[
            FlowById {
                file: "123-Town5",
                index: 186,
            },
            Oarc {
                stage: "F016r",
                layer: 0,
            },
        ],
    ),
    (
        "Upper Skyloft - Owlan's Crystals",
        &[
            FlowById {
                file: "118-Town3",
                index: 157,
            },
            Oarc {
                stage: "F001r",
                layer: 0,
            },
        ],
    ),
    (
        "Batreaux's House - 5 Crystals",
        &[
            FlowById {
                file: "121-AkumaKun",
                index: 21,
            },
            Oarc {
                stage: "F012r",
                layer: 0,
            },
        ],
    ),
    (
        "Batreaux's House - 10 Crystals",
        &[
            FlowById {
                file: "121-AkumaKun",
                index: 42,
            },
            Oarc {
                stage: "F012r",
                layer: 0,
            },
        ],
    ),
    (
        "Batreaux's House - 30 Crystals",
        &[
            FlowById {
                file: "121-AkumaKun",
                index: 24,
            },
            Oarc {
                stage: "F012r",
                layer: 0,
            },
        ],
    ),
    (
        "Batreaux's House - 30 Crystals Chest",
        &[TBox {
            stage: "F012r",
            room: 0,
            layer: 0,
            tbox_id: 69,
        }],
    ),
    (
        "Batreaux's House - 40 Crystals",
        &[
            FlowById {
                file: "121-AkumaKun",
                index: 49,
            },
            Oarc {
                stage: "F012r",
                layer: 0,
            },
        ],
    ),
    (
        "Batreaux's House - 50 Crystals",
        &[
            FlowById {
                file: "121-AkumaKun",
                index: 27,
            },
            Oarc {
                stage: "F012r",
                layer: 0,
            },
        ],
    ),
    (
        "Batreaux's House - 70 Crystals",
        &[
            FlowById {
                file: "121-AkumaKun",
                index: 161,
            },
            Oarc {
                stage: "F012r",
                layer: 0,
            },
        ],
    ),
    (
        "Batreaux's House - 70 Crystals Second Reward",
        &[
            FlowById {
                file: "121-AkumaKun",
                index: 163,
            },
            Oarc {
                stage: "F012r",
                layer: 0,
            },
        ],
    ),
    (
        "Batreaux's House - 80 Crystals",
        &[
            FlowById {
                file: "121-AkumaKun",
                index: 37,
            },
            Oarc {
                stage: "F012r",
                layer: 0,
            },
        ],
    ),
    ("Beedle's Shop - 300 Rupee Item", &[ShpSmpl { index: 20 }]),
    ("Beedle's Shop - 600 Rupee Item", &[ShpSmpl { index: 21 }]),
    ("Beedle's Shop - 1200 Rupee Item", &[ShpSmpl { index: 22 }]),
    ("Beedle's Shop - 800 Rupee Item", &[ShpSmpl { index: 26 }]),
    ("Beedle's Shop - 1600 Rupee Item", &[ShpSmpl { index: 23 }]),
    (
        "Beedle's Shop - First 100 Rupee Item",
        &[ShpSmpl { index: 24 }],
    ),
    (
        "Beedle's Shop - Second 100 Rupee Item",
        &[ShpSmpl { index: 17 }],
    ),
    (
        "Beedle's Shop - Third 100 Rupee Item",
        &[ShpSmpl { index: 18 }],
    ),
    ("Beedle's Shop - 50 Rupee Item", &[ShpSmpl { index: 25 }]),
    ("Beedle's Shop - 1000 Rupee Item", &[ShpSmpl { index: 27 }]),
    ("Upper Skyloft - Crystal in Link's Room", &[]),
    ("Central Skyloft - Crystal on Light Tower", &[]),
    ("Skyloft Village - Crystal near Pumpkin Patch", &[]),
    (
        "Central Skyloft - Crystal in Orielle and Parrow's House",
        &[],
    ),
    ("Central Skyloft - Crystal between Wooden Planks", &[]),
    ("Upper Skyloft - Crystal in Knight Academy Plant", &[]),
    ("Central Skyloft - Crystal on West Cliff", &[]),
    ("Central Skyloft - Crystal after Waterfall Cave", &[]),
    ("Central Skyloft - Crystal in Loftwing Prison", &[]),
    ("Upper Skyloft - Crystal in Sparring Hall", &[]),
    ("Central Skyloft - Crystal on Waterfall Island", &[]),
    ("Upper Skyloft - Crystal in Zelda's Room", &[]),
    (
        "Sky - Lumpy Pumpkin - Outside Goddess Chest",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Sky - Lumpy Pumpkin - Goddess Chest on the Roof",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 87,
        }],
    ),
    (
        "Sky - Lumpy Pumpkin - Chandelier",
        &[Chandel {
            stage: "F011r",
            room: 0,
            layer: 0,
        }],
    ),
    (
        "Sky - Lumpy Pumpkin - Harp Minigame",
        &[
            FlowById {
                file: "117-Pumpkin",
                index: 305,
            },
            Oarc {
                stage: "F011r",
                layer: 0,
            },
        ],
    ),
    (
        "Sky - Bamboo Island Goddess Chest",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 82,
        }],
    ),
    (
        "Sky - Goddess Chest on Island next to Bamboo Island",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 71,
        }],
    ),
    (
        "Sky - Goddess Chest in Cave on Island Next to Bamboo Island",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 83,
        }],
    ),
    (
        "Sky - Beedle's Island Goddess Chest",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 89,
        }],
    ),
    (
        "Sky - Beedle's Island Cage Goddess Chest",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 81,
        }],
    ),
    (
        "Sky - Northeast Island Goddess Chest behind Bombable Rocks",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 72,
        }],
    ),
    (
        "Sky - Northeast Island Cage Goddess Chest",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 74,
        }],
    ),
    (
        "Sky - Goddess Chest on Island Closest to Faron Pillar",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 65,
        }],
    ),
    (
        "Sky - Goddess Chest outside Volcanic Island",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 67,
        }],
    ),
    (
        "Sky - Goddess Chest inside Volcanic Island",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 68,
        }],
    ),
    (
        "Sky - Goddess Chest under Fun Fun Island",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 86,
        }],
    ),
    (
        "Sky - Southwest Triple Island Upper Goddess Chest",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Sky - Southwest Triple Island Lower Goddess Chest",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 84,
        }],
    ),
    (
        "Sky - Southwest Triple Island Cage Goddess Chest",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 75,
        }],
    ),
    (
        "Sky - Dodoh's Crystals",
        &[
            FlowById {
                file: "110-DivingGame",
                index: 60,
            },
            Oarc {
                stage: "F020",
                layer: 0,
            },
        ],
    ),
    (
        "Sky - Fun Fun Island Minigame -- 500 Rupees",
        &[
            FlowById {
                file: "110-DivingGame",
                index: 19,
            },
            Oarc {
                stage: "F020",
                layer: 2,
            },
        ],
    ),
    (
        "Sky - Orielle's Crystals",
        &[
            FlowById {
                file: "115-Town2",
                index: 225,
            },
            Oarc {
                stage: "F020",
                layer: 0,
            },
        ],
    ),
    (
        "Sky - Kina's Crystals",
        &[
            FlowById {
                file: "117-Pumpkin",
                index: 386,
            },
            Oarc {
                stage: "F020",
                layer: 0,
            },
        ],
    ),
    (
        "Sky - Beedle's Crystals",
        &[
            FlowById {
                file: "105-Terry",
                index: 115,
            },
            Oarc {
                stage: "F020",
                layer: 0,
            },
        ],
    ),
    (
        "Sky - Chest in Breakable Boulder near Fun Fun Island",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 70,
        }],
    ),
    (
        "Sky - Chest in Breakable Boulder near Lumpy Pumpkin",
        &[TBox {
            stage: "F020",
            room: 0,
            layer: 0,
            tbox_id: 69,
        }],
    ),
    ("Sky - Crystal outside Lumpy Pumpkin", &[]),
    ("Sky - Crystal inside Lumpy Pumpkin", &[]),
    ("Sky - Crystal on Beedle's Ship", &[]),
    (
        "Thunderhead - Goddess Chest outside Isle of Songs",
        &[TBox {
            stage: "F023",
            room: 0,
            layer: 0,
            tbox_id: 92,
        }],
    ),
    (
        "Thunderhead - Goddess Chest on top of Isle of Songs",
        &[TBox {
            stage: "F023",
            room: 0,
            layer: 0,
            tbox_id: 85,
        }],
    ),
    (
        "Thunderhead - East Island Goddess Chest",
        &[TBox {
            stage: "F023",
            room: 0,
            layer: 0,
            tbox_id: 73,
        }],
    ),
    (
        "Thunderhead - East Island Chest",
        &[TBox {
            stage: "F023",
            room: 0,
            layer: 0,
            tbox_id: 94,
        }],
    ),
    (
        "Thunderhead - Bug Heaven Goddess Chest",
        &[TBox {
            stage: "F023",
            room: 0,
            layer: 0,
            tbox_id: 88,
        }],
    ),
    (
        "Thunderhead - First Goddess Chest on Mogma Mitts Island",
        &[TBox {
            stage: "F023",
            room: 0,
            layer: 0,
            tbox_id: 77,
        }],
    ),
    (
        "Thunderhead - Second Goddess Chest on Mogma Mitts Island",
        &[TBox {
            stage: "F023",
            room: 0,
            layer: 0,
            tbox_id: 76,
        }],
    ),
    (
        "Thunderhead - Bug Heaven -- 10 Bugs in 3 Minutes",
        &[
            FlowById {
                file: "116-InsectGame",
                index: 69,
            },
            Oarc {
                stage: "F023",
                layer: 0,
            },
        ],
    ),
    (
        "Thunderhead - Song from Levias",
        &[
            FlowByName {
                file: "120-Nushi",
                name: "give item after levias",
            },
            Oarc {
                stage: "F023",
                layer: 0,
            },
        ],
    ),
    (
        "Thunderhead - Isle of Songs - Farore's Courage",
        &[SwSB {
            stage: "F010r",
            room: 0,
            layer: 0,
            index: 0,
        }],
    ),
    (
        "Thunderhead - Isle of Songs - Nayru's Wisdom",
        &[SwSB {
            stage: "F010r",
            room: 0,
            layer: 0,
            index: 1,
        }],
    ),
    (
        "Thunderhead - Isle of Songs - Din's Power",
        &[SwSB {
            stage: "F010r",
            room: 0,
            layer: 0,
            index: 2,
        }],
    ),
    (
        "Sealed Grounds - Chest inside Sealed Temple",
        &[TBox {
            stage: "F402",
            room: 2,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Sealed Grounds - Song from Impa",
        &[
            FlowById {
                file: "501-Inpa",
                index: 267,
            },
            Oarc {
                stage: "F402",
                layer: 2,
            },
        ],
    ),
    (
        "Sealed Grounds - Gorko's Goddess Wall Reward",
        &[
            FlowById {
                file: "503-Goron",
                index: 630,
            },
            Oarc {
                stage: "F400",
                layer: 0,
            },
        ],
    ),
    (
        "Sealed Grounds - Zelda's Blessing",
        &[
            FlowById {
                file: "502-CenterFieldBack",
                index: 17,
            },
            Oarc {
                stage: "F404",
                layer: 1,
            },
        ],
    ),
    (
        "Faron Woods - Item on Tree",
        &[Item {
            stage: "F100",
            room: 0,
            layer: 0,
            flag: 68,
        }],
    ),
    (
        "Faron Woods - Slingshot",
        &[
            FlowById {
                file: "200-Forest",
                index: 595,
            },
            Oarc {
                stage: "F100",
                layer: 0,
            },
        ],
    ),
    (
        "Faron Woods - Deep Woods Chest",
        &[TBox {
            stage: "F101",
            room: 0,
            layer: 0,
            tbox_id: 74,
        }],
    ),
    (
        "Faron Woods - Item behind Bombable Rock",
        &[Item {
            stage: "F100",
            room: 0,
            layer: 0,
            flag: 33,
        }],
    ),
    (
        "Faron Woods - Chest behind Bombable Rocks near Erla",
        &[TBox {
            stage: "F100",
            room: 0,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Faron Woods - Chest inside Great Tree",
        &[TBox {
            stage: "F100_1",
            room: 0,
            layer: 0,
            tbox_id: 84,
        }],
    ),
    (
        "Faron Woods - Rupee on Great Tree North Branch",
        &[Item {
            stage: "F100",
            room: 0,
            layer: 0,
            flag: 43,
        }],
    ),
    (
        "Faron Woods - Rupee on Great Tree West Branch",
        &[Item {
            stage: "F100",
            room: 0,
            layer: 0,
            flag: 44,
        }],
    ),
    (
        "Faron Woods - Rupee on Platform near Floria Door",
        &[Item {
            stage: "F100",
            room: 0,
            layer: 0,
            flag: 40,
        }],
    ),
    (
        "Faron Woods - Rupee on Hollow Tree Root",
        &[Item {
            stage: "F100",
            room: 0,
            layer: 0,
            flag: 42,
        }],
    ),
    (
        "Faron Woods - Rupee on Hollow Tree Branch",
        &[Item {
            stage: "F100",
            room: 0,
            layer: 0,
            flag: 41,
        }],
    ),
    (
        "Lake Floria - Lake Floria Chest",
        &[TBox {
            stage: "F102",
            room: 3,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Lake Floria - Dragon Lair East Chest",
        &[TBox {
            stage: "F102_2",
            room: 0,
            layer: 0,
            tbox_id: 85,
        }],
    ),
    (
        "Lake Floria - Dragon Lair South Chest",
        &[TBox {
            stage: "F102_2",
            room: 0,
            layer: 0,
            tbox_id: 84,
        }],
    ),
    (
        "Lake Floria - Rupee under Central Boulder",
        &[Item {
            stage: "F102",
            room: 2,
            layer: 0,
            flag: 60,
        }],
    ),
    (
        "Lake Floria - Right Rupee behind Northwest Boulder",
        &[Item {
            stage: "F102",
            room: 2,
            layer: 0,
            flag: 61,
        }],
    ),
    (
        "Lake Floria - Left Rupee behind Northwest Boulder",
        &[Item {
            stage: "F102",
            room: 2,
            layer: 0,
            flag: 62,
        }],
    ),
    (
        "Lake Floria - Rupee behind Southwest Boulder",
        &[Item {
            stage: "F102",
            room: 2,
            layer: 0,
            flag: 63,
        }],
    ),
    (
        "Lake Floria - Rupee on High Ledge outside Ancient Cistern Entrance",
        &[Item {
            stage: "F102_1",
            room: 0,
            layer: 0,
            flag: 64,
        }],
    ),
    (
        "Flooded Faron Woods - Water Dragon's Reward",
        &[
            FlowByName {
                file: "204-ForestF3",
                name: "Give item after Faron SotH CS",
            },
            Oarc {
                stage: "F103_1",
                layer: 0,
            },
        ],
    ),
    (
        "Eldin Volcano - Chest behind Bombable Wall in First Room",
        &[TBox {
            stage: "F200",
            room: 1,
            layer: 0,
            tbox_id: 72,
        }],
    ),
    (
        "Eldin Volcano - Chest after Crawlspace",
        &[TBox {
            stage: "F200",
            room: 2,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Eldin Volcano - Chest behind Bombable Wall near Cliff",
        &[TBox {
            stage: "F200",
            room: 2,
            layer: 0,
            tbox_id: 73,
        }],
    ),
    (
        "Eldin Volcano - Item on Cliff",
        &[Item {
            stage: "F200",
            room: 2,
            layer: 0,
            flag: 102,
        }],
    ),
    (
        "Eldin Volcano - Chest behind Bombable Wall near Volcano Ascent",
        &[TBox {
            stage: "F200",
            room: 2,
            layer: 0,
            tbox_id: 71,
        }],
    ),
    (
        "Eldin Volcano - Rupee on Ledge before First Room",
        &[Item {
            stage: "F200",
            room: 0,
            layer: 0,
            flag: 41,
        }],
    ),
    (
        "Eldin Volcano - Rupee behind Bombable Wall in First Room",
        &[Item {
            stage: "F200",
            room: 1,
            layer: 0,
            flag: 13,
        }],
    ),
    (
        "Eldin Volcano - Rupee in Crawlspace in First Room",
        &[Item {
            stage: "F200",
            room: 1,
            layer: 0,
            flag: 19,
        }],
    ),
    (
        "Eldin Volcano - Southeast Rupee above Mogma Turf Entrance",
        &[Item {
            stage: "F200",
            room: 2,
            layer: 0,
            flag: 125,
        }],
    ),
    (
        "Eldin Volcano - North Rupee above Mogma Turf Entrance",
        &[Item {
            stage: "F200",
            room: 2,
            layer: 0,
            flag: 123,
        }],
    ),
    (
        "Eldin Volcano - Left Rupee behind Bombable Wall on First Slope",
        &[Item {
            stage: "F200",
            room: 4,
            layer: 0,
            flag: 45,
        }],
    ),
    (
        "Eldin Volcano - Right Rupee behind Bombable Wall on First Slope",
        &[Item {
            stage: "F200",
            room: 4,
            layer: 0,
            flag: 11,
        }],
    ),
    (
        "Eldin Volcano - Digging Spot in front of Earth Temple",
        &[Soil {
            stage: "F200",
            room: 4,
            layer: 1,
            flag: 8,
        }],
    ),
    (
        "Eldin Volcano - Digging Spot below Tower",
        &[Soil {
            stage: "F200",
            room: 4,
            layer: 1,
            flag: 9,
        }],
    ),
    (
        "Eldin Volcano - Digging Spot behind Boulder on Sandy Slope",
        &[Soil {
            stage: "F200",
            room: 4,
            layer: 1,
            flag: 12,
        }],
    ),
    (
        "Eldin Volcano - Digging Spot after Vents",
        &[Soil {
            stage: "F200",
            room: 6,
            layer: 1,
            flag: 10,
        }],
    ),
    (
        "Eldin Volcano - Digging Spot after Draining Lava",
        &[Soil {
            stage: "F200",
            room: 2,
            layer: 1,
            flag: 64,
        }],
    ),
    (
        "Mogma Turf - Free Fall Chest",
        &[TBox {
            stage: "F210",
            room: 0,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Mogma Turf - Chest behind Bombable Wall at Entrance",
        &[TBox {
            stage: "F210",
            room: 0,
            layer: 0,
            tbox_id: 65,
        }],
    ),
    (
        "Mogma Turf - Sand Slide Chest",
        &[TBox {
            stage: "F210",
            room: 0,
            layer: 0,
            tbox_id: 68,
        }],
    ),
    (
        "Mogma Turf - Digging Mitts Fight",
        &[
            FlowById {
                file: "300-Mountain",
                index: 6,
            },
            FlowById {
                file: "300-Mountain",
                index: 135,
            },
            Oarc {
                stage: "F210",
                layer: 0,
            },
        ],
    ),
    (
        "Mogma Turf - Chest behind Bombable Wall in Fire Maze",
        &[TBox {
            stage: "F210",
            room: 0,
            layer: 0,
            tbox_id: 70,
        }],
    ),
    (
        "Volcano Summit - Item behind Digging",
        &[Item {
            stage: "F201_3",
            room: 0,
            layer: 0,
            flag: 104,
        }],
    ),
    (
        "Volcano Summit - Chest behind Bombable Wall in Waterfall Area",
        &[TBox {
            stage: "F201_4",
            room: 0,
            layer: 0,
            tbox_id: 95,
        }],
    ),
    (
        "Bokoblin Base - Plats' Gift",
        &[
            FlowByName {
                file: "305-MountainF3",
                name: "Plats' Gift",
            },
            Oarc {
                stage: "F202",
                layer: 1,
            },
        ],
    ),
    (
        "Bokoblin Base - Chest near Bone Bridge",
        &[TBox {
            stage: "F202",
            room: 2,
            layer: 1,
            tbox_id: 70,
        }],
    ),
    (
        "Bokoblin Base - Chest on Cliff",
        &[TBox {
            stage: "F202",
            room: 2,
            layer: 1,
            tbox_id: 66,
        }],
    ),
    (
        "Bokoblin Base - Chest near Drawbridge",
        &[TBox {
            stage: "F202",
            room: 2,
            layer: 1,
            tbox_id: 67,
        }],
    ),
    (
        "Bokoblin Base - Chest East of Earth Temple Entrance",
        &[TBox {
            stage: "F202",
            room: 4,
            layer: 1,
            tbox_id: 68,
        }],
    ),
    (
        "Bokoblin Base - Chest West of Earth Temple Entrance",
        &[TBox {
            stage: "F202",
            room: 4,
            layer: 1,
            tbox_id: 69,
        }],
    ),
    (
        "Bokoblin Base - First Chest in Volcano Summit",
        &[
            TBox {
                stage: "F201_2",
                room: 0,
                layer: 0,
                tbox_id: 72,
            },
            TBox {
                stage: "F201_1",
                room: 0,
                layer: 4,
                tbox_id: 72,
            },
        ],
    ),
    (
        "Bokoblin Base - Raised Chest in Volcano Summit",
        &[
            TBox {
                stage: "F201_2",
                room: 0,
                layer: 0,
                tbox_id: 73,
            },
            TBox {
                stage: "F201_1",
                room: 0,
                layer: 4,
                tbox_id: 73,
            },
        ],
    ),
    (
        "Bokoblin Base - Chest in Volcano Summit Alcove",
        &[
            TBox {
                stage: "F201_2",
                room: 0,
                layer: 0,
                tbox_id: 71,
            },
            TBox {
                stage: "F201_1",
                room: 0,
                layer: 4,
                tbox_id: 71,
            },
        ],
    ),
    (
        "Bokoblin Base - Fire Dragon's Reward",
        &[
            FlowByName {
                file: "305-MountainF3",
                name: "Give item after Eldin SotH CS",
            },
            Oarc {
                stage: "F221",
                layer: 0,
            },
        ],
    ),
    (
        "Lanayru Mine - Chest behind First Landing",
        &[TBox {
            stage: "F300_1",
            room: 0,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Lanayru Mine - Chest near First Timeshift Stone",
        &[TBox {
            stage: "F300_1",
            room: 1,
            layer: 0,
            tbox_id: 65,
        }],
    ),
    (
        "Lanayru Mine - Chest behind Statue",
        &[TBox {
            stage: "F300_1",
            room: 2,
            layer: 0,
            tbox_id: 67,
        }],
    ),
    (
        "Lanayru Mine - Chest at the End of Mine",
        &[TBox {
            stage: "F300_1",
            room: 2,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Lanayru Desert - Chest near Party Wheel",
        &[TBox {
            stage: "F300",
            room: 0,
            layer: 0,
            tbox_id: 70,
        }],
    ),
    (
        "Lanayru Desert - Chest near Hook Beetle Fight",
        &[TBox {
            stage: "F300",
            room: 0,
            layer: 0,
            tbox_id: 84,
        }],
    ),
    (
        "Lanayru Desert - Hook Beetle Fight",
        &[
            FlowById {
                file: "400-Desert",
                index: 8,
            },
            Oarc {
                stage: "F300",
                layer: 0,
            },
        ],
    ),
    (
        "Lanayru Desert - Secret Passageway Chest",
        &[TBox {
            stage: "F300",
            room: 0,
            layer: 0,
            tbox_id: 74,
        }],
    ),
    (
        "Lanayru Desert - Chest on top of Lanayru Mining Facility",
        &[TBox {
            stage: "F300",
            room: 0,
            layer: 1,
            tbox_id: 83,
        }],
    ),
    (
        "Lanayru Desert - Chest on Platform near Lightning Node",
        &[TBox {
            stage: "F300",
            room: 0,
            layer: 0,
            tbox_id: 72,
        }],
    ),
    (
        "Lanayru Desert - Chest on Platform near Fire Node",
        &[TBox {
            stage: "F300",
            room: 0,
            layer: 0,
            tbox_id: 73,
        }],
    ),
    (
        "Lanayru Desert - Chest near Sand Oasis",
        &[TBox {
            stage: "F300",
            room: 0,
            layer: 0,
            tbox_id: 71,
        }],
    ),
    (
        "Lanayru Desert - Lightning Node - First Chest",
        &[TBox {
            stage: "F300_2",
            room: 0,
            layer: 0,
            tbox_id: 75,
        }],
    ),
    (
        "Lanayru Desert - Lightning Node - Second Chest",
        &[TBox {
            stage: "F300_2",
            room: 0,
            layer: 0,
            tbox_id: 76,
        }],
    ),
    (
        "Lanayru Desert - Lightning Node - Raised Chest near Generator",
        &[TBox {
            stage: "F300_2",
            room: 0,
            layer: 0,
            tbox_id: 77,
        }],
    ),
    (
        "Lanayru Desert - Fire Node - Shortcut Chest",
        &[TBox {
            stage: "F300_3",
            room: 0,
            layer: 0,
            tbox_id: 79,
        }],
    ),
    (
        "Lanayru Desert - Fire Node - First Small Chest",
        &[TBox {
            stage: "F300_3",
            room: 0,
            layer: 0,
            tbox_id: 78,
        }],
    ),
    (
        "Lanayru Desert - Fire Node - Second Small Chest",
        &[TBox {
            stage: "F300_3",
            room: 0,
            layer: 0,
            tbox_id: 80,
        }],
    ),
    (
        "Lanayru Desert - Fire Node - Left Ending Chest",
        &[TBox {
            stage: "F300_3",
            room: 0,
            layer: 0,
            tbox_id: 81,
        }],
    ),
    (
        "Lanayru Desert - Fire Node - Right Ending Chest",
        &[TBox {
            stage: "F300_3",
            room: 0,
            layer: 0,
            tbox_id: 82,
        }],
    ),
    (
        "Lanayru Caves - Chest",
        &[TBox {
            stage: "F303",
            room: 0,
            layer: 0,
            tbox_id: 127,
        }],
    ),
    (
        "Lanayru Caves - Golo's Gift",
        &[
            FlowById {
                file: "404-DesertF3",
                index: 127,
            },
            Oarc {
                stage: "F303",
                layer: 0,
            },
        ],
    ),
    (
        "Lanayru Sand Sea - Ancient Harbour - Rupee on First Pillar",
        &[Item {
            stage: "F301",
            room: 0,
            layer: 0,
            flag: 92,
        }],
    ),
    (
        "Lanayru Sand Sea - Ancient Harbour - Left Rupee on Entrance Crown",
        &[Item {
            stage: "F301",
            room: 0,
            layer: 0,
            flag: 91,
        }],
    ),
    (
        "Lanayru Sand Sea - Ancient Harbour - Right Rupee on Entrance Crown",
        &[Item {
            stage: "F301",
            room: 0,
            layer: 0,
            flag: 93,
        }],
    ),
    (
        "Lanayru Sand Sea - Skipper's Retreat - Chest after Moblin",
        &[TBox {
            stage: "F301_3",
            room: 0,
            layer: 0,
            tbox_id: 78,
        }],
    ),
    (
        "Lanayru Sand Sea - Skipper's Retreat - Chest on top of Cacti Pillar",
        &[TBox {
            stage: "F301_3",
            room: 0,
            layer: 0,
            tbox_id: 76,
        }],
    ),
    (
        "Lanayru Sand Sea - Skipper's Retreat - Chest in Shack",
        &[TBox {
            stage: "F301_5",
            room: 0,
            layer: 0,
            tbox_id: 65,
        }],
    ),
    (
        "Lanayru Sand Sea - Skipper's Retreat - Skydive Chest",
        &[TBox {
            stage: "F301_3",
            room: 0,
            layer: 0,
            tbox_id: 77,
        }],
    ),
    (
        "Lanayru Sand Sea - Rickety Coaster -- Heart Stopping Track in 1'05",
        &[
            FlowById {
                file: "406-TrolleyRace",
                index: 77,
            },
            Oarc {
                stage: "F301_4",
                layer: 0,
            },
        ],
    ),
    (
        "Lanayru Sand Sea - Pirate Stronghold - First Chest",
        &[TBox {
            stage: "F301_2",
            room: 4,
            layer: 0,
            tbox_id: 75,
        }],
    ),
    (
        "Lanayru Sand Sea - Pirate Stronghold - Second Chest",
        &[TBox {
            stage: "F301_2",
            room: 5,
            layer: 0,
            tbox_id: 73,
        }],
    ),
    (
        "Lanayru Sand Sea - Pirate Stronghold - Third Chest",
        &[TBox {
            stage: "F301_2",
            room: 6,
            layer: 0,
            tbox_id: 74,
        }],
    ),
    (
        "Lanayru Sand Sea - Pirate Stronghold - Rupee on West Sea Pillar",
        &[Item {
            stage: "F301_6",
            room: 0,
            layer: 0,
            flag: 11,
        }],
    ),
    (
        "Lanayru Sand Sea - Pirate Stronghold - Rupee on East Sea Pillar",
        &[Item {
            stage: "F301_6",
            room: 0,
            layer: 0,
            flag: 12,
        }],
    ),
    (
        "Lanayru Sand Sea - Pirate Stronghold - Rupee on Bird Statue Pillar or Nose",
        &[
            Item {
                stage: "F301_6",
                room: 0,
                layer: 1,
                flag: 13,
            },
            Item {
                stage: "F301_6",
                room: 0,
                layer: 2,
                flag: 13,
            },
        ],
    ),
    (
        "Lanayru Gorge - Item on Pillar",
        &[Item {
            stage: "F302",
            room: 0,
            layer: 0,
            flag: 9,
        }],
    ),
    (
        "Lanayru Gorge - Life Tree Seedling",
        &[Soil {
            stage: "F302",
            room: 0,
            layer: 0,
            flag: 30,
        }],
    ),
    (
        "Lanayru Gorge - Thunder Dragon's Reward",
        &[
            FlowByName {
                file: "404-DesertF3",
                name: "give item after Healing Thunderdragon",
            },
            Oarc {
                stage: "F302",
                layer: 0,
            },
        ],
    ),
    (
        "Skyview - Chest on Tree Branch",
        &[TBox {
            stage: "D100",
            room: 2,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Skyview - Digging Spot in Crawlspace",
        &[Soil {
            stage: "D100",
            room: 4,
            layer: 0,
            flag: 15,
        }],
    ),
    (
        "Skyview - Chest behind Two Eyes",
        &[TBox {
            stage: "D100",
            room: 4,
            layer: 0,
            tbox_id: 67,
        }],
    ),
    (
        "Skyview - Beetle",
        &[
            TBox {
                stage: "D100",
                room: 10,
                layer: 1,
                tbox_id: 65,
            },
            TBox {
                stage: "D100",
                room: 10,
                layer: 2,
                tbox_id: 65,
            },
        ],
    ),
    (
        "Skyview - Item behind Bars",
        &[Item {
            stage: "D100",
            room: 5,
            layer: 0,
            flag: 103,
        }],
    ),
    (
        "Skyview - Rupee in Southeast Tunnel",
        &[Item {
            stage: "D100",
            room: 5,
            layer: 0,
            flag: 65,
        }],
    ),
    (
        "Skyview - Rupee in Southwest Tunnel",
        &[Item {
            stage: "D100",
            room: 5,
            layer: 0,
            flag: 67,
        }],
    ),
    (
        "Skyview - Rupee in East Tunnel",
        &[Item {
            stage: "D100",
            room: 5,
            layer: 0,
            flag: 66,
        }],
    ),
    (
        "Skyview - Chest behind Three Eyes",
        &[TBox {
            stage: "D100",
            room: 7,
            layer: 0,
            tbox_id: 68,
        }],
    ),
    (
        "Skyview - Chest near Boss Door",
        &[TBox {
            stage: "D100",
            room: 9,
            layer: 0,
            tbox_id: 70,
        }],
    ),
    (
        "Skyview - Boss Key Chest",
        &[TBox {
            stage: "D100",
            room: 9,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Skyview - Heart Container",
        &[
            HeartCo {
                stage: "B100",
                room: 0,
                layer: 1,
            },
            HeartCo {
                stage: "B100",
                room: 0,
                layer: 2,
            },
            HeartCo {
                stage: "B100",
                room: 0,
                layer: 3,
            },
            HeartCo {
                stage: "B100",
                room: 0,
                layer: 4,
            },
        ],
    ),
    (
        "Skyview - Rupee on Spring Pillar",
        &[Item {
            stage: "B100_1",
            room: 0,
            layer: 0,
            flag: 109,
        }],
    ),
    (
        "Skyview - Ruby Tablet",
        &[
            FlowById {
                file: "201-ForestD1",
                index: 6,
            },
            Oarc {
                stage: "B100_1",
                layer: 0,
            },
        ],
    ),
    (
        "Earth Temple - Vent Chest",
        &[TBox {
            stage: "D200",
            room: 1,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Earth Temple - Rupee above Drawbridge",
        &[Item {
            stage: "D200",
            room: 1,
            layer: 0,
            flag: 25,
        }],
    ),
    (
        "Earth Temple - Chest behind Bombable Rock",
        &[TBox {
            stage: "D200",
            room: 1,
            layer: 0,
            tbox_id: 69,
        }],
    ),
    (
        "Earth Temple - Chest Left of Main Room Bridge",
        &[TBox {
            stage: "D200",
            room: 1,
            layer: 0,
            tbox_id: 70,
        }],
    ),
    (
        "Earth Temple - Chest in West Room",
        &[TBox {
            stage: "D200",
            room: 0,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Earth Temple - Bomb Bag",
        &[TBox {
            stage: "D200",
            room: 3,
            layer: 0,
            tbox_id: 65,
        }],
    ),
    (
        "Earth Temple - Ledd's Gift",
        &[
            FlowById {
                file: "301-MountainD1",
                index: 16,
            },
            Oarc {
                stage: "D200",
                layer: 0,
            },
        ],
    ),
    (
        "Earth Temple - Rupee in Lava Tunnel",
        &[Item {
            stage: "D200",
            room: 2,
            layer: 0,
            flag: 21,
        }],
    ),
    (
        "Earth Temple - Chest Guarded by Lizalfos",
        &[TBox {
            stage: "D200",
            room: 1,
            layer: 0,
            tbox_id: 67,
        }],
    ),
    (
        "Earth Temple - Boss Key Chest",
        &[TBox {
            stage: "D200",
            room: 4,
            layer: 0,
            tbox_id: 68,
        }],
    ),
    (
        "Earth Temple - Heart Container",
        &[
            HeartCo {
                stage: "B200",
                room: 10,
                layer: 1,
            },
            HeartCo {
                stage: "B200",
                room: 10,
                layer: 2,
            },
        ],
    ),
    (
        "Earth Temple - Amber Tablet",
        &[
            FlowById {
                file: "301-MountainD1",
                index: 22,
            },
            Oarc {
                stage: "B210",
                layer: 0,
            },
        ],
    ),
    (
        "Lanayru Mining Facility - Chest behind Bars",
        &[TBox {
            stage: "D300",
            room: 0,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Lanayru Mining Facility - First Chest in Hub Room",
        &[TBox {
            stage: "D300_1",
            room: 5,
            layer: 0,
            tbox_id: 70,
        }],
    ),
    (
        "Lanayru Mining Facility - Chest in Key Locked Room",
        &[TBox {
            stage: "D300",
            room: 2,
            layer: 0,
            tbox_id: 65,
        }],
    ),
    (
        "Lanayru Mining Facility - Gust Bellows",
        &[TBox {
            stage: "D300",
            room: 4,
            layer: 0,
            tbox_id: 68,
        }],
    ),
    (
        "Lanayru Mining Facility - Chest inside Gust Bellows Room",
        &[TBox {
            stage: "D300",
            room: 4,
            layer: 0,
            tbox_id: 76,
        }],
    ),
    (
        "Lanayru Mining Facility - Chest in First West Room",
        &[TBox {
            stage: "D300",
            room: 3,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Lanayru Mining Facility - Chest after Armos Fight",
        &[TBox {
            stage: "D300",
            room: 6,
            layer: 0,
            tbox_id: 69,
        }],
    ),
    (
        "Lanayru Mining Facility - Chest behind First Crawlspace",
        &[
            TBox {
                stage: "D300_1",
                room: 9,
                layer: 0,
                tbox_id: 72,
            },
            TBox {
                stage: "D300",
                room: 9,
                layer: 0,
                tbox_id: 72,
            },
        ],
    ),
    (
        "Lanayru Mining Facility - Chest in Spike Maze",
        &[
            TBox {
                stage: "D300_1",
                room: 7,
                layer: 0,
                tbox_id: 73,
            },
            TBox {
                stage: "D300",
                room: 7,
                layer: 0,
                tbox_id: 73,
            },
        ],
    ),
    (
        "Lanayru Mining Facility - Boss Key Chest",
        &[TBox {
            stage: "D300_1",
            room: 8,
            layer: 0,
            tbox_id: 71,
        }],
    ),
    (
        "Lanayru Mining Facility - Shortcut Chest in Main Hub",
        &[TBox {
            stage: "D300_1",
            room: 5,
            layer: 0,
            tbox_id: 74,
        }],
    ),
    (
        "Lanayru Mining Facility - Heart Container",
        &[
            HeartCo {
                stage: "B300",
                room: 0,
                layer: 1,
            },
            HeartCo {
                stage: "B300",
                room: 0,
                layer: 3,
            },
        ],
    ),
    (
        "Lanayru Mining Facility - Goddess Harp",
        &[
            FlowById {
                file: "400-Desert",
                index: 286,
            },
            Oarc {
                stage: "F300_5",
                layer: 0,
            },
        ],
    ),
    (
        "Ancient Cistern - Chest in East Part",
        &[TBox {
            stage: "D101",
            room: 1,
            layer: 0,
            tbox_id: 67,
        }],
    ),
    (
        "Ancient Cistern - Rupee in East Part in Main Tunnel",
        &[Item {
            stage: "D101",
            room: 2,
            layer: 0,
            flag: 34,
        }],
    ),
    (
        "Ancient Cistern - Rupee in East Part in Cubby",
        &[Item {
            stage: "D101",
            room: 2,
            layer: 0,
            flag: 68,
        }],
    ),
    (
        "Ancient Cistern - First Rupee in East Part in Short Tunnel",
        &[Item {
            stage: "D101",
            room: 2,
            layer: 0,
            flag: 65,
        }],
    ),
    (
        "Ancient Cistern - Second Rupee in East Part in Short Tunnel",
        &[Item {
            stage: "D101",
            room: 2,
            layer: 0,
            flag: 66,
        }],
    ),
    (
        "Ancient Cistern - Third Rupee in East Part in Short Tunnel",
        &[Item {
            stage: "D101",
            room: 2,
            layer: 0,
            flag: 67,
        }],
    ),
    (
        "Ancient Cistern - Whip",
        &[TBox {
            stage: "D101",
            room: 7,
            layer: 0,
            tbox_id: 69,
        }],
    ),
    (
        "Ancient Cistern - Chest after Whip Hooks",
        &[TBox {
            stage: "D101",
            room: 0,
            layer: 0,
            tbox_id: 65,
        }],
    ),
    (
        "Ancient Cistern - Rupee in East Hand",
        &[Item {
            stage: "D101",
            room: 0,
            layer: 0,
            flag: 92,
        }],
    ),
    (
        "Ancient Cistern - Rupee in West Hand",
        &[Item {
            stage: "D101",
            room: 0,
            layer: 0,
            flag: 93,
        }],
    ),
    (
        "Ancient Cistern - Chest near Vines",
        &[TBox {
            stage: "D101",
            room: 0,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Ancient Cistern - Chest behind the Waterfall",
        &[TBox {
            stage: "D101",
            room: 3,
            layer: 0,
            tbox_id: 84,
        }],
    ),
    (
        "Ancient Cistern - Bokoblin",
        &[EBc {
            stage: "D101",
            room: 4,
            layer: 0,
            id: 0xFC00,
        }],
    ),
    (
        "Ancient Cistern - Boss Key Chest",
        &[TBox {
            stage: "D101",
            room: 4,
            layer: 0,
            tbox_id: 68,
        }],
    ),
    (
        "Ancient Cistern - Heart Container",
        &[
            HeartCo {
                stage: "B101",
                room: 0,
                layer: 1,
            },
            HeartCo {
                stage: "B101",
                room: 0,
                layer: 3,
            },
        ],
    ),
    (
        "Ancient Cistern - Farore's Flame",
        &[
            FlowByName {
                file: "202-ForestD2",
                name: "give item after beating ancient cistern",
            },
            Oarc {
                stage: "B101_1",
                layer: 0,
            },
        ],
    ),
    (
        "Sandship - Chest behind Combination Lock",
        &[TBox {
            stage: "D301",
            room: 10,
            layer: 0,
            tbox_id: 69,
        }],
    ),
    (
        "Sandship - Bow",
        &[TBox {
            stage: "D301",
            room: 15,
            layer: 0,
            tbox_id: 72,
        }],
    ),
    (
        "Sandship - Chest at the Stern",
        &[TBox {
            stage: "D301",
            room: 0,
            layer: 0,
            tbox_id: 127,
        }],
    ),
    (
        "Sandship - Chest before 4-Door Corridor",
        &[TBox {
            stage: "D301",
            room: 3,
            layer: 0,
            tbox_id: 71,
        }],
    ),
    (
        "Sandship - Treasure Room First Chest",
        &[TBox {
            stage: "D301",
            room: 9,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Sandship - Treasure Room Second Chest",
        &[TBox {
            stage: "D301",
            room: 9,
            layer: 0,
            tbox_id: 65,
        }],
    ),
    (
        "Sandship - Treasure Room Third Chest",
        &[TBox {
            stage: "D301",
            room: 9,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Sandship - Treasure Room Fourth Chest",
        &[TBox {
            stage: "D301",
            room: 9,
            layer: 0,
            tbox_id: 67,
        }],
    ),
    (
        "Sandship - Treasure Room Fifth Chest",
        &[TBox {
            stage: "D301",
            room: 9,
            layer: 0,
            tbox_id: 68,
        }],
    ),
    (
        "Sandship - Robot in Brig's Reward",
        &[
            FlowById {
                file: "401-DesertD2",
                index: 14,
            },
            Oarc {
                stage: "D301",
                layer: 4,
            },
        ],
    ),
    (
        "Sandship - Boss Key Chest",
        &[TBox {
            stage: "D301",
            room: 14,
            layer: 3,
            tbox_id: 73,
        }],
    ),
    (
        "Sandship - Heart Container",
        &[
            HeartCo {
                stage: "B301",
                room: 0,
                layer: 1,
            },
            HeartCo {
                stage: "D301",
                room: 0,
                layer: 1,
            },
        ],
    ),
    (
        "Sandship - Nayru's Flame",
        &[
            FlowById {
                file: "401-DesertD2",
                index: 45,
            },
            Oarc {
                stage: "B301",
                layer: 1,
            },
            Oarc {
                stage: "D301",
                layer: 1,
            },
        ],
    ),
    (
        "Fire Sanctuary - Chest in First Room",
        &[TBox {
            stage: "D201",
            room: 0,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Fire Sanctuary - Chest in Second Room",
        &[
            TBox {
                stage: "D201_1",
                room: 1,
                layer: 0,
                tbox_id: 74,
            },
            TBox {
                stage: "D201",
                room: 1,
                layer: 0,
                tbox_id: 74,
            },
        ],
    ),
    (
        "Fire Sanctuary - Chest near First Trapped Mogma",
        &[TBox {
            stage: "D201_1",
            room: 5,
            layer: 0,
            tbox_id: 69,
        }],
    ),
    (
        "Fire Sanctuary - First Chest in Water Fruit Room",
        &[TBox {
            stage: "D201_1",
            room: 7,
            layer: 0,
            tbox_id: 73,
        }],
    ),
    (
        "Fire Sanctuary - Second Chest in Water Fruit Room",
        &[TBox {
            stage: "D201_1",
            room: 7,
            layer: 0,
            tbox_id: 72,
        }],
    ),
    (
        "Fire Sanctuary - Mogma Mitts",
        &[TBox {
            stage: "D201_1",
            room: 5,
            layer: 0,
            tbox_id: 68,
        }],
    ),
    (
        "Fire Sanctuary - Chest on Balcony",
        &[
            TBox {
                stage: "D201_1",
                room: 6,
                layer: 0,
                tbox_id: 70,
            },
            TBox {
                stage: "D201",
                room: 6,
                layer: 0,
                tbox_id: 70,
            },
        ],
    ),
    (
        "Fire Sanctuary - Chest after Second Trapped Mogma",
        &[
            TBox {
                stage: "D201_1",
                room: 2,
                layer: 0,
                tbox_id: 65,
            },
            TBox {
                stage: "D201",
                room: 2,
                layer: 0,
                tbox_id: 65,
            },
        ],
    ),
    (
        "Fire Sanctuary - Chest after Bombable Wall",
        &[TBox {
            stage: "D201_1",
            room: 11,
            layer: 0,
            tbox_id: 71,
        }],
    ),
    (
        "Fire Sanctuary - Plats' Chest",
        &[TBox {
            stage: "D201",
            room: 3,
            layer: 0,
            tbox_id: 66,
        }],
    ),
    (
        "Fire Sanctuary - Chest in Staircase Room",
        &[TBox {
            stage: "D201",
            room: 9,
            layer: 0,
            tbox_id: 75,
        }],
    ),
    (
        "Fire Sanctuary - Boss Key Chest",
        &[TBox {
            stage: "D201",
            room: 4,
            layer: 0,
            tbox_id: 67,
        }],
    ),
    (
        "Fire Sanctuary - Heart Container",
        &[
            HeartCo {
                stage: "B201",
                room: 0,
                layer: 1,
            },
            HeartCo {
                stage: "B201",
                room: 0,
                layer: 2,
            },
        ],
    ),
    (
        "Fire Sanctuary - Din's Flame",
        &[
            FlowById {
                file: "304-MountainD2",
                index: 5,
            },
            Oarc {
                stage: "B201_1",
                layer: 0,
            },
        ],
    ),
    (
        "Sky Keep - First Chest",
        &[TBox {
            stage: "D003_7",
            room: 0,
            layer: 0,
            tbox_id: 64,
        }],
    ),
    (
        "Sky Keep - Chest after Dreadfuse",
        &[TBox {
            stage: "D003_6",
            room: 0,
            layer: 0,
            tbox_id: 65,
        }],
    ),
    (
        "Sky Keep - Triforce of Wisdom",
        &[Item {
            stage: "D003_8",
            room: 0,
            layer: 1,
            flag: 62,
        }],
    ),
    (
        "Sky Keep - Triforce of Power",
        &[Item {
            stage: "D003_8",
            room: 0,
            layer: 2,
            flag: 61,
        }],
    ),
    (
        "Sky Keep - Triforce of Courage",
        &[Item {
            stage: "D003_8",
            room: 0,
            layer: 3,
            flag: 64,
        }],
    ),
    (
        "Sky Keep - Rupee in Fire Sanctuary Room in Alcove",
        &[Item {
            stage: "D003_2",
            room: 0,
            layer: 0,
            flag: 36,
        }],
    ),
    (
        "Skyloft Silent Realm - Stone of Trials",
        &[WarpObj {
            stage: "S000",
            room: 0,
            layer: 2,
        }],
    ),
    (
        "Faron Silent Realm - Water Scale",
        &[WarpObj {
            stage: "S100",
            room: 0,
            layer: 2,
        }],
    ),
    (
        "Lanayru Silent Realm - Clawshots",
        &[WarpObj {
            stage: "S300",
            room: 0,
            layer: 2,
        }],
    ),
    (
        "Eldin Silent Realm - Fireshield Earrings",
        &[WarpObj {
            stage: "S200",
            room: 2,
            layer: 2,
        }],
    ),
];
