[package]
name = "verification-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nlzss11 = { version = "1.0.1" }
bzs = { path = "../bzs" }
u8file = { path = "../u8file" }
